### ISSUE TITLE
Chart export isn't working when running product from Eclipse

### ISSUE THREAD

**Issue by jasper-d** [sebastiangoetz/slr-toolkit#60]
When running the product from Eclipse ("Launch an Eclipse application" in app.product) PDF export of Charts does not work. Running the product build by Maven works.

This is caused by a version conflict between several Batik bundles which are dependencies of org.eclipse.birt.chart.device.pdf.
org.eclipse.birt.chart.device.pdf requires some Batik bundles with a version < 1.7.0 while other components require the same bundles with a version >= 1.7.0.

It's a regression, the issue was fixed in 9453ae7610 and 108bf9ac1. See also the original issue #25.

The console output when launching from Eclipse looks like this:

```
!ENTRY org.eclipse.birt.chart.device.pdf 4 0 2016-02-05 19:24:57.497
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.birt.chart.device.pdf [12]
Unresolved requirement: Require-Bundle: org.apache.batik.transcoder; bundle-version="[1.6.0,1.7.0)"

at org.eclipse.osgi.container.Module.start(Module.java:434)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)`
```

**Comment by sebastiangoetz** [comment]
fixed with [release 0.2.8](https://github.com/sebastiangoetz/slr-toolkit/releases/tag/0.2.8)
